// <auto-generated />
using System;
using ECDLink.DataAccessLayer.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace ECDLink.DataAccessLayer.Migrations
{
    [DbContext(typeof(AuthenticationDbContext))]
    [Migration("20220730045556_AddCPFA")]
    partial class AddCPFA
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("ECDLink.DataAccessLayer.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("ContactPreference")
                        .HasColumnType("text");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .HasColumnType("text");

                    b.Property<Guid?>("GenderId")
                        .HasColumnType("uuid");

                    b.Property<string>("IdNumber")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSouthAfricanCitizen")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastSeen")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NickFirstName")
                        .HasColumnType("text");

                    b.Property<string>("NickFullName")
                        .HasColumnType("text");

                    b.Property<string>("NickSurname")
                        .HasColumnType("text");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("ProfileImageUrl")
                        .HasColumnType("text");

                    b.Property<Guid?>("RaceId")
                        .HasColumnType("uuid");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<string>("Surname")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("VerifiedByHomeAffairs")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("GenderId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("RaceId");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("ECDLink.DataAccessLayer.Entities.AuditLog.AuditLog", b =>
                {
                    b.Property<Guid>("AuditLogTypeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime>("InsertedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasIndex("AuditLogTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("AuditLog");
                });

            modelBuilder.Entity("ECDLink.DataAccessLayer.Entities.AuditLog.AuditLogType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("EnumId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("InsertedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("AuditLogType");
                });

            modelBuilder.Entity("ECDLink.DataAccessLayer.Entities.Caregiver.Caregiver", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdditionalFirstName")
                        .HasColumnType("text");

                    b.Property<string>("AdditionalPhoneNumber")
                        .HasColumnType("text");

                    b.Property<string>("AdditionalSurname")
                        .HasColumnType("text");

                    b.Property<bool>("Contribution")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("EducationId")
                        .HasColumnType("uuid");

                    b.Property<string>("EmergencyContactFirstName")
                        .HasColumnType("text");

                    b.Property<string>("EmergencyContactPhoneNumber")
                        .HasColumnType("text");

                    b.Property<string>("EmergencyContactSurname")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .HasColumnType("text");

                    b.Property<string>("IdNumber")
                        .HasColumnType("text");

                    b.Property<DateTime>("InsertedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("JoinReferencePanel")
                        .HasColumnType("boolean");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<Guid?>("RelationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SiteAddressId")
                        .HasColumnType("uuid");

                    b.Property<string>("Surname")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("EducationId");

                    b.HasIndex("RelationId");

                    b.HasIndex("SiteAddressId");

                    b.ToTable("Caregiver");
                });

            modelBuilder.Entity("ECDLink.DataAccessLayer.Entities.Classroom.Attendance", b =>
                {
                    b.Property<Guid>("ClassroomProgrammeId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<int>("WeekOfYear")
                        .HasColumnType("integer");

                    b.Property<DateTime>("AttendanceDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("Attended")
                        .HasColumnType("boolean");

                    b.Property<int>("MonthOfYear")
                        .HasColumnType("integer");

                    b.Property<string>("ParentRecordId")
                        .HasColumnType("text");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("ClassroomProgrammeId", "UserId", "WeekOfYear");

                    b.HasIndex("UserId");

                    b.ToTable("Attendance");
                });

            modelBuilder.Entity("ECDLink.DataAccessLayer.Entities.Classroom.ClassProgramme", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ClassroomGroupId")
                        .HasColumnType("uuid");

                    b.Property<string>("Hierarchy")
                        .HasColumnType("text");

                    b.Property<DateTime>("InsertedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsFullDay")
                        .HasColumnType("boolean");

                    b.Property<int>("MeetingDay")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ProgrammeStartDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClassroomGroupId");

                    b.ToTable("ClassProgramme");
                });

            modelBuilder.Entity("ECDLink.DataAccessLayer.Entities.Classroom.Classroom", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ClassroomImageUrl")
                        .HasColumnType("text");

                    b.Property<bool?>("DoesOwnerTeach")
                        .HasColumnType("boolean");

                    b.Property<string>("Hierarchy")
                        .HasColumnType("text");

                    b.Property<DateTime>("InsertedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsPrinciple")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int?>("NumberOfAssistants")
                        .HasColumnType("integer");

                    b.Property<int?>("NumberOfOtherAssistants")
                        .HasColumnType("integer");

                    b.Property<int?>("NumberPractitioners")
                        .HasColumnType("integer");

                    b.Property<Guid?>("SiteAddressId")
                        .HasColumnType("uuid");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SiteAddressId");

                    b.HasIndex("UserId");

                    b.ToTable("Classroom");
                });

            modelBuilder.Entity("ECDLink.DataAccessLayer.Entities.Classroom.ClassroomGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClassroomId")
                        .HasColumnType("uuid");

                    b.Property<string>("Hierarchy")
                        .HasColumnType("text");

                    b.Property<DateTime>("InsertedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<Guid?>("ProgrammeTypeId")
                        .HasColumnType("uuid");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClassroomId");

                    b.HasIndex("ProgrammeTypeId");

                    b.ToTable("ClassroomGroup");
                });

            modelBuilder.Entity("ECDLink.DataAccessLayer.Entities.Classroom.DailyProgramme", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Day")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DayDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("InsertedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("LargeGroupActivityId")
                        .HasColumnType("integer");

                    b.Property<string>("MessageBoardText")
                        .HasColumnType("text");

                    b.Property<Guid>("ProgrammeId")
                        .HasColumnType("uuid");

                    b.Property<int>("SmallGroupActivityId")
                        .HasColumnType("integer");

                    b.Property<int>("StoryActivityId")
                        .HasColumnType("integer");

                    b.Property<int>("StoryBookId")
                        .HasColumnType("integer");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProgrammeId");

                    b.ToTable("ProgrammeDay");
                });

            modelBuilder.Entity("ECDLink.DataAccessLayer.Entities.Classroom.Learner", b =>
                {
                    b.Property<Guid>("ClassroomGroupId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("Hierarchy")
                        .HasColumnType("text");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("InsertedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("OtherAttendanceReason")
                        .HasColumnType("text");

                    b.Property<Guid?>("ProgrammeAttendanceReasonId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartedAttendance")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("StoppedAttendance")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("ClassroomGroupId", "UserId");

                    b.HasIndex("ProgrammeAttendanceReasonId");

                    b.HasIndex("UserId");

                    b.ToTable("Learner");
                });

            modelBuilder.Entity("ECDLink.DataAccessLayer.Entities.Classroom.Programme", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClassroomId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("InsertedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("PreferredLanguage")
                        .HasColumnType("text");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClassroomId");

                    b.ToTable("Programme");
                });

            modelBuilder.Entity("ECDLink.DataAccessLayer.Entities.Classroom.ProgrammeAttendanceReason", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("InsertedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("ProgrammeAttendanceReason");
                });

            modelBuilder.Entity("ECDLink.DataAccessLayer.Entities.Classroom.ProgrammeType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("EnumId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("InsertedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("ProgrammeType");
                });

            modelBuilder.Entity("ECDLink.DataAccessLayer.Entities.Documents.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ChildId")
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedUserId")
                        .HasColumnType("text");

                    b.Property<Guid>("DocumentTypeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("InsertedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<Guid?>("PractitionerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reference")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<Guid>("WorkflowStatusId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ChildId");

                    b.HasIndex("DocumentTypeId");

                    b.HasIndex("PractitionerId");

                    b.HasIndex("UserId");

                    b.HasIndex("WorkflowStatusId");

                    b.ToTable("Document");
                });

            modelBuilder.Entity("ECDLink.DataAccessLayer.Entities.Documents.DocumentType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("EnumId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("InsertedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("DocumentType");
                });

            modelBuilder.Entity("ECDLink.DataAccessLayer.Entities.Documents.UserConsent", b =>
                {
                    b.Property<int>("ConsentId")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("ConsentType")
                        .HasColumnType("text");

                    b.Property<string>("CreatedUserId")
                        .HasColumnType("text");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("InsertedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("ConsentId", "UserId");

                    b.ToTable("UserConsent");
                });

            modelBuilder.Entity("ECDLink.DataAccessLayer.Entities.Education", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime>("InsertedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("Education");
                });

            modelBuilder.Entity("ECDLink.DataAccessLayer.Entities.Gender", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime>("InsertedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("Gender");
                });

            modelBuilder.Entity("ECDLink.DataAccessLayer.Entities.Grant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CaregiverId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime>("InsertedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("CaregiverId");

                    b.ToTable("Grant");
                });

            modelBuilder.Entity("ECDLink.DataAccessLayer.Entities.Language", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime>("InsertedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Locale")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("Language");
                });

            modelBuilder.Entity("ECDLink.DataAccessLayer.Entities.Navigation.Navigation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Icon")
                        .HasColumnType("text");

                    b.Property<DateTime>("InsertedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Route")
                        .HasColumnType("text");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("Navigation");
                });

            modelBuilder.Entity("ECDLink.DataAccessLayer.Entities.Navigation.NavigationPermission", b =>
                {
                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("NavigationId")
                        .HasColumnType("uuid");

                    b.HasKey("PermissionId", "NavigationId");

                    b.HasIndex("NavigationId");

                    b.ToTable("NavigationPermission");
                });

            modelBuilder.Entity("ECDLink.DataAccessLayer.Entities.Notes.Note", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BodyText")
                        .HasColumnType("text");

                    b.Property<string>("CreatedUserId")
                        .HasColumnType("text");

                    b.Property<DateTime>("InsertedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<Guid>("NoteTypeId")
                        .HasColumnType("uuid");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("NoteTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("Note");
                });

            modelBuilder.Entity("ECDLink.DataAccessLayer.Entities.Notes.NoteType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("EnumId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("InsertedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("NormalizedName")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("NoteType");
                });

            modelBuilder.Entity("ECDLink.DataAccessLayer.Entities.Notifications.MessageTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("InsertedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.Property<string>("Protocol")
                        .HasColumnType("text");

                    b.Property<string>("TemplateType")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("MessageTemplate");
                });

            modelBuilder.Entity("ECDLink.DataAccessLayer.Entities.Notifications.ShortenUrlEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Clicked")
                        .HasColumnType("integer");

                    b.Property<string>("Hierarchy")
                        .HasColumnType("text");

                    b.Property<DateTime>("InsertedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("MessageType")
                        .HasColumnType("text");

                    b.Property<string>("URL")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ShortUrl");
                });

            modelBuilder.Entity("ECDLink.DataAccessLayer.Entities.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Grouping")
                        .HasColumnType("text")
                        .HasColumnName("Grouping");

                    b.Property<DateTime>("InsertedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("(now())");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Name");

                    b.Property<string>("NormalizedName")
                        .HasColumnType("text")
                        .HasColumnName("NormalizedName");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("Permission");
                });

            modelBuilder.Entity("ECDLink.DataAccessLayer.Entities.Province", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime>("InsertedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("Province");
                });

            modelBuilder.Entity("ECDLink.DataAccessLayer.Entities.Race", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime>("InsertedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("Race");
                });

            modelBuilder.Entity("ECDLink.DataAccessLayer.Entities.ReasonForLeaving", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime>("InsertedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("ReasonForLeaving");
                });

            modelBuilder.Entity("ECDLink.DataAccessLayer.Entities.Relation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime>("InsertedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("Relation");
                });

            modelBuilder.Entity("ECDLink.DataAccessLayer.Entities.Reports.ChildProgressReport", b =>
                {
                    b.Property<Guid>("ClassroomGroupId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChildId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Hierarchy")
                        .HasColumnType("text");

                    b.Property<DateTime>("InsertedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("ReportContent")
                        .HasColumnType("text");

                    b.Property<DateTime>("ReportDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("ClassroomGroupId", "ChildId", "Id");

                    b.HasIndex("ChildId");

                    b.ToTable("ChildProgressReport");
                });

            modelBuilder.Entity("ECDLink.DataAccessLayer.Entities.RolePermission", b =>
                {
                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("PermissionId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("RolePermission");
                });

            modelBuilder.Entity("ECDLink.DataAccessLayer.Entities.SiteAddress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AddressLine1")
                        .HasColumnType("text");

                    b.Property<string>("AddressLine2")
                        .HasColumnType("text");

                    b.Property<string>("AddressLine3")
                        .HasColumnType("text");

                    b.Property<DateTime>("InsertedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("PostalCode")
                        .HasColumnType("text");

                    b.Property<Guid>("ProvinceId")
                        .HasColumnType("uuid");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Ward")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProvinceId");

                    b.ToTable("SiteAddress");
                });

            modelBuilder.Entity("ECDLink.DataAccessLayer.Entities.SystemSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FullPath")
                        .HasColumnType("text");

                    b.Property<string>("Grouping")
                        .HasColumnType("text");

                    b.Property<DateTime>("InsertedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsSystemValue")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SystemSetting");
                });

            modelBuilder.Entity("ECDLink.DataAccessLayer.Entities.Users.Absentees", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AbsentDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("InsertedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LoggedBy")
                        .HasColumnType("text");

                    b.Property<Guid?>("PractitionerId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ProgramId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<string>("ReassignedClass")
                        .HasColumnType("text");

                    b.Property<string>("ReassignedToPractitioner")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PractitionerId");

                    b.HasIndex("ProgramId");

                    b.HasIndex("UserId");

                    b.ToTable("Absentees");
                });

            modelBuilder.Entity("ECDLink.DataAccessLayer.Entities.Users.Child", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Allergies")
                        .HasColumnType("text");

                    b.Property<Guid?>("CaregiverId")
                        .HasColumnType("uuid");

                    b.Property<string>("Disabilities")
                        .HasColumnType("text");

                    b.Property<string>("Hierarchy")
                        .HasColumnType("text");

                    b.Property<DateTime>("InsertedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("LanguageId")
                        .HasColumnType("uuid");

                    b.Property<string>("OtherHealthConditions")
                        .HasColumnType("text");

                    b.Property<Guid?>("ReasonForLeavingId")
                        .HasColumnType("uuid");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<Guid?>("WorkflowStatusId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CaregiverId");

                    b.HasIndex("LanguageId");

                    b.HasIndex("ReasonForLeavingId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.HasIndex("WorkflowStatusId");

                    b.ToTable("Child");
                });

            modelBuilder.Entity("ECDLink.DataAccessLayer.Entities.Users.Coach", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AreaOfOperation")
                        .HasColumnType("text");

                    b.Property<Guid?>("FranchisorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Hierarchy")
                        .HasColumnType("text");

                    b.Property<DateTime>("InsertedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("SecondaryAreaOfOperation")
                        .HasColumnType("text");

                    b.Property<string>("Signature")
                        .HasColumnType("text");

                    b.Property<Guid?>("SiteAddressId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SiteAddressId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Coach");
                });

            modelBuilder.Entity("ECDLink.DataAccessLayer.Entities.Users.Franchisor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AreaOfOperation")
                        .HasColumnType("text");

                    b.Property<DateTime>("InsertedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("SecondaryAreaOfOperation")
                        .HasColumnType("text");

                    b.Property<Guid?>("SiteAddressId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SiteAddressId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Franchisor");
                });

            modelBuilder.Entity("ECDLink.DataAccessLayer.Entities.Users.Mapping.CareGiverGrant", b =>
                {
                    b.Property<Guid>("GrantId")
                        .HasColumnType("uuid");

                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.HasKey("GrantId", "Id");

                    b.ToTable("CareGiverGrant");
                });

            modelBuilder.Entity("ECDLink.DataAccessLayer.Entities.Users.Mapping.UserGrant", b =>
                {
                    b.Property<Guid>("GrantId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("GrantId", "UserId");

                    b.ToTable("UserGrants");
                });

            modelBuilder.Entity("ECDLink.DataAccessLayer.Entities.Users.Practitioner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AttendanceRegisterLink")
                        .HasColumnType("text");

                    b.Property<string>("CoachHierarchy")
                        .HasColumnType("text");

                    b.Property<bool?>("ConsentForPhoto")
                        .HasColumnType("boolean");

                    b.Property<string>("Hierarchy")
                        .HasColumnType("text");

                    b.Property<DateTime>("InsertedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsFundaAppAdmin")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsPrincipal")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsTrainee")
                        .HasColumnType("boolean");

                    b.Property<string>("LanguageUsedInGroups")
                        .HasColumnType("text");

                    b.Property<int?>("MaxChildren")
                        .HasColumnType("integer");

                    b.Property<int?>("MonthSinceFranchisee")
                        .HasColumnType("integer");

                    b.Property<bool?>("IsRegistered")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("ParentFees")
                        .HasColumnType("numeric");

                    b.Property<string>("PrincipalHierarchy")
                        .HasColumnType("text");

                    b.Property<string>("Signature")
                        .HasColumnType("text");

                    b.Property<Guid?>("SiteAddressId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SiteAddressId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Practitioner");
                });

            modelBuilder.Entity("ECDLink.DataAccessLayer.Entities.Workflow.WorkflowStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("EnumId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("InsertedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("WorkflowStatusTypeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowStatusTypeId");

                    b.ToTable("WorkflowStatus");
                });

            modelBuilder.Entity("ECDLink.DataAccessLayer.Entities.Workflow.WorkflowStatusType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime>("InsertedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("WorkflowStatusType");
                });

            modelBuilder.Entity("ECDLink.DataAccessLayer.Hierarchy.Entities.HierarchyEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("InsertedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<string>("SystemType")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("Hierarchy");
                });

            modelBuilder.Entity("ECDLink.DataAccessLayer.Hierarchy.Entities.UserHierarchyEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Hierarchy")
                        .HasColumnType("text");

                    b.Property<DateTime>("InsertedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("NamedTypePath")
                        .HasColumnType("text");

                    b.Property<string>("ParentId")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("UserType")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserHierarchy");
                });

            modelBuilder.Entity("ECDLink.DataAccessLayer.Jobs.JobNotification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Protocol")
                        .HasColumnType("text");

                    b.Property<int>("TemplateType")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<DateTime>("UserLastSeen")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("JobNotification");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("ECDLink.DataAccessLayer.Entities.ApplicationUser", b =>
                {
                    b.HasOne("ECDLink.DataAccessLayer.Entities.Gender", "Gender")
                        .WithMany()
                        .HasForeignKey("GenderId");

                    b.HasOne("ECDLink.DataAccessLayer.Entities.Race", "Race")
                        .WithMany()
                        .HasForeignKey("RaceId");

                    b.Navigation("Gender");

                    b.Navigation("Race");
                });

            modelBuilder.Entity("ECDLink.DataAccessLayer.Entities.AuditLog.AuditLog", b =>
                {
                    b.HasOne("ECDLink.DataAccessLayer.Entities.AuditLog.AuditLogType", "AuditLogType")
                        .WithMany()
                        .HasForeignKey("AuditLogTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ECDLink.DataAccessLayer.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("AuditLogType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ECDLink.DataAccessLayer.Entities.Caregiver.Caregiver", b =>
                {
                    b.HasOne("ECDLink.DataAccessLayer.Entities.Education", "Education")
                        .WithMany()
                        .HasForeignKey("EducationId");

                    b.HasOne("ECDLink.DataAccessLayer.Entities.Relation", "Relation")
                        .WithMany()
                        .HasForeignKey("RelationId");

                    b.HasOne("ECDLink.DataAccessLayer.Entities.SiteAddress", "SiteAddress")
                        .WithMany()
                        .HasForeignKey("SiteAddressId");

                    b.Navigation("Education");

                    b.Navigation("Relation");

                    b.Navigation("SiteAddress");
                });

            modelBuilder.Entity("ECDLink.DataAccessLayer.Entities.Classroom.Attendance", b =>
                {
                    b.HasOne("ECDLink.DataAccessLayer.Entities.Classroom.ClassProgramme", "ClassroomProgramme")
                        .WithMany()
                        .HasForeignKey("ClassroomProgrammeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ECDLink.DataAccessLayer.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClassroomProgramme");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ECDLink.DataAccessLayer.Entities.Classroom.ClassProgramme", b =>
                {
                    b.HasOne("ECDLink.DataAccessLayer.Entities.Classroom.ClassroomGroup", "ClassroomGroup")
                        .WithMany("ClassProgrammes")
                        .HasForeignKey("ClassroomGroupId");

                    b.Navigation("ClassroomGroup");
                });

            modelBuilder.Entity("ECDLink.DataAccessLayer.Entities.Classroom.Classroom", b =>
                {
                    b.HasOne("ECDLink.DataAccessLayer.Entities.SiteAddress", "SiteAddress")
                        .WithMany()
                        .HasForeignKey("SiteAddressId");

                    b.HasOne("ECDLink.DataAccessLayer.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("SiteAddress");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ECDLink.DataAccessLayer.Entities.Classroom.ClassroomGroup", b =>
                {
                    b.HasOne("ECDLink.DataAccessLayer.Entities.Classroom.Classroom", "Classroom")
                        .WithMany("ClassroomGroups")
                        .HasForeignKey("ClassroomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ECDLink.DataAccessLayer.Entities.Classroom.ProgrammeType", "ProgrammeType")
                        .WithMany()
                        .HasForeignKey("ProgrammeTypeId");

                    b.Navigation("Classroom");

                    b.Navigation("ProgrammeType");
                });

            modelBuilder.Entity("ECDLink.DataAccessLayer.Entities.Classroom.DailyProgramme", b =>
                {
                    b.HasOne("ECDLink.DataAccessLayer.Entities.Classroom.Programme", "Programme")
                        .WithMany("DailyProgrammes")
                        .HasForeignKey("ProgrammeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Programme");
                });

            modelBuilder.Entity("ECDLink.DataAccessLayer.Entities.Classroom.Learner", b =>
                {
                    b.HasOne("ECDLink.DataAccessLayer.Entities.Classroom.ClassroomGroup", "ClassroomGroup")
                        .WithMany("Learners")
                        .HasForeignKey("ClassroomGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ECDLink.DataAccessLayer.Entities.Classroom.ProgrammeAttendanceReason", "ProgrammeAttendanceReason")
                        .WithMany()
                        .HasForeignKey("ProgrammeAttendanceReasonId");

                    b.HasOne("ECDLink.DataAccessLayer.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClassroomGroup");

                    b.Navigation("ProgrammeAttendanceReason");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ECDLink.DataAccessLayer.Entities.Classroom.Programme", b =>
                {
                    b.HasOne("ECDLink.DataAccessLayer.Entities.Classroom.Classroom", "Classroom")
                        .WithMany("Programmes")
                        .HasForeignKey("ClassroomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Classroom");
                });

            modelBuilder.Entity("ECDLink.DataAccessLayer.Entities.Documents.Document", b =>
                {
                    b.HasOne("ECDLink.DataAccessLayer.Entities.Users.Child", null)
                        .WithMany("Documents")
                        .HasForeignKey("ChildId");

                    b.HasOne("ECDLink.DataAccessLayer.Entities.Documents.DocumentType", "DocumentType")
                        .WithMany()
                        .HasForeignKey("DocumentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ECDLink.DataAccessLayer.Entities.Users.Practitioner", null)
                        .WithMany("Documents")
                        .HasForeignKey("PractitionerId");

                    b.HasOne("ECDLink.DataAccessLayer.Entities.ApplicationUser", "User")
                        .WithMany("Documents")
                        .HasForeignKey("UserId");

                    b.HasOne("ECDLink.DataAccessLayer.Entities.Workflow.WorkflowStatus", "WorkflowStatus")
                        .WithMany()
                        .HasForeignKey("WorkflowStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DocumentType");

                    b.Navigation("User");

                    b.Navigation("WorkflowStatus");
                });

            modelBuilder.Entity("ECDLink.DataAccessLayer.Entities.Grant", b =>
                {
                    b.HasOne("ECDLink.DataAccessLayer.Entities.Caregiver.Caregiver", null)
                        .WithMany("Grants")
                        .HasForeignKey("CaregiverId");
                });

            modelBuilder.Entity("ECDLink.DataAccessLayer.Entities.Navigation.NavigationPermission", b =>
                {
                    b.HasOne("ECDLink.DataAccessLayer.Entities.Navigation.Navigation", "Navigation")
                        .WithMany()
                        .HasForeignKey("NavigationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ECDLink.DataAccessLayer.Entities.Permission", "Permission")
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Navigation");

                    b.Navigation("Permission");
                });

            modelBuilder.Entity("ECDLink.DataAccessLayer.Entities.Notes.Note", b =>
                {
                    b.HasOne("ECDLink.DataAccessLayer.Entities.Notes.NoteType", "NoteType")
                        .WithMany()
                        .HasForeignKey("NoteTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ECDLink.DataAccessLayer.Entities.ApplicationUser", "User")
                        .WithMany("Notes")
                        .HasForeignKey("UserId");

                    b.Navigation("NoteType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ECDLink.DataAccessLayer.Entities.Reports.ChildProgressReport", b =>
                {
                    b.HasOne("ECDLink.DataAccessLayer.Entities.Users.Child", "Child")
                        .WithMany()
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ECDLink.DataAccessLayer.Entities.Classroom.ClassroomGroup", "ClassroomGroup")
                        .WithMany()
                        .HasForeignKey("ClassroomGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Child");

                    b.Navigation("ClassroomGroup");
                });

            modelBuilder.Entity("ECDLink.DataAccessLayer.Entities.RolePermission", b =>
                {
                    b.HasOne("ECDLink.DataAccessLayer.Entities.Permission", "Permission")
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ECDLink.DataAccessLayer.Entities.SiteAddress", b =>
                {
                    b.HasOne("ECDLink.DataAccessLayer.Entities.Province", "Province")
                        .WithMany()
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Province");
                });

            modelBuilder.Entity("ECDLink.DataAccessLayer.Entities.Users.Absentees", b =>
                {
                    b.HasOne("ECDLink.DataAccessLayer.Entities.Users.Practitioner", "Practitioner")
                        .WithMany()
                        .HasForeignKey("PractitionerId");

                    b.HasOne("ECDLink.DataAccessLayer.Entities.Classroom.Programme", "Program")
                        .WithMany()
                        .HasForeignKey("ProgramId");

                    b.HasOne("ECDLink.DataAccessLayer.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Practitioner");

                    b.Navigation("Program");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ECDLink.DataAccessLayer.Entities.Users.Child", b =>
                {
                    b.HasOne("ECDLink.DataAccessLayer.Entities.Caregiver.Caregiver", "Caregiver")
                        .WithMany()
                        .HasForeignKey("CaregiverId");

                    b.HasOne("ECDLink.DataAccessLayer.Entities.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId");

                    b.HasOne("ECDLink.DataAccessLayer.Entities.ReasonForLeaving", "ReasonForLeaving")
                        .WithMany()
                        .HasForeignKey("ReasonForLeavingId");

                    b.HasOne("ECDLink.DataAccessLayer.Entities.ApplicationUser", "User")
                        .WithOne("childObjectData")
                        .HasForeignKey("ECDLink.DataAccessLayer.Entities.Users.Child", "UserId");

                    b.HasOne("ECDLink.DataAccessLayer.Entities.Workflow.WorkflowStatus", "WorkflowStatus")
                        .WithMany()
                        .HasForeignKey("WorkflowStatusId");

                    b.Navigation("Caregiver");

                    b.Navigation("Language");

                    b.Navigation("ReasonForLeaving");

                    b.Navigation("User");

                    b.Navigation("WorkflowStatus");
                });

            modelBuilder.Entity("ECDLink.DataAccessLayer.Entities.Users.Coach", b =>
                {
                    b.HasOne("ECDLink.DataAccessLayer.Entities.SiteAddress", "SiteAddress")
                        .WithMany()
                        .HasForeignKey("SiteAddressId");

                    b.HasOne("ECDLink.DataAccessLayer.Entities.ApplicationUser", "User")
                        .WithOne("coachObjectData")
                        .HasForeignKey("ECDLink.DataAccessLayer.Entities.Users.Coach", "UserId");

                    b.Navigation("SiteAddress");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ECDLink.DataAccessLayer.Entities.Users.Franchisor", b =>
                {
                    b.HasOne("ECDLink.DataAccessLayer.Entities.SiteAddress", "SiteAddress")
                        .WithMany()
                        .HasForeignKey("SiteAddressId");

                    b.HasOne("ECDLink.DataAccessLayer.Entities.ApplicationUser", "User")
                        .WithOne("franchisorObjectData")
                        .HasForeignKey("ECDLink.DataAccessLayer.Entities.Users.Franchisor", "UserId");

                    b.Navigation("SiteAddress");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ECDLink.DataAccessLayer.Entities.Users.Mapping.CareGiverGrant", b =>
                {
                    b.HasOne("ECDLink.DataAccessLayer.Entities.Grant", "Grant")
                        .WithMany()
                        .HasForeignKey("GrantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grant");
                });

            modelBuilder.Entity("ECDLink.DataAccessLayer.Entities.Users.Mapping.UserGrant", b =>
                {
                    b.HasOne("ECDLink.DataAccessLayer.Entities.Grant", "Grant")
                        .WithMany()
                        .HasForeignKey("GrantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grant");
                });

            modelBuilder.Entity("ECDLink.DataAccessLayer.Entities.Users.Practitioner", b =>
                {
                    b.HasOne("ECDLink.DataAccessLayer.Entities.SiteAddress", "SiteAddress")
                        .WithMany()
                        .HasForeignKey("SiteAddressId");

                    b.HasOne("ECDLink.DataAccessLayer.Entities.ApplicationUser", "User")
                        .WithOne("practitionerObjectData")
                        .HasForeignKey("ECDLink.DataAccessLayer.Entities.Users.Practitioner", "UserId");

                    b.Navigation("SiteAddress");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ECDLink.DataAccessLayer.Entities.Workflow.WorkflowStatus", b =>
                {
                    b.HasOne("ECDLink.DataAccessLayer.Entities.Workflow.WorkflowStatusType", "WorkflowStatusType")
                        .WithMany()
                        .HasForeignKey("WorkflowStatusTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkflowStatusType");
                });

            modelBuilder.Entity("ECDLink.DataAccessLayer.Hierarchy.Entities.UserHierarchyEntity", b =>
                {
                    b.HasOne("ECDLink.DataAccessLayer.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ECDLink.DataAccessLayer.Jobs.JobNotification", b =>
                {
                    b.HasOne("ECDLink.DataAccessLayer.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ECDLink.DataAccessLayer.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ECDLink.DataAccessLayer.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ECDLink.DataAccessLayer.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ECDLink.DataAccessLayer.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ECDLink.DataAccessLayer.Entities.ApplicationUser", b =>
                {
                    b.Navigation("childObjectData");

                    b.Navigation("coachObjectData");

                    b.Navigation("Documents");

                    b.Navigation("franchisorObjectData");

                    b.Navigation("Notes");

                    b.Navigation("practitionerObjectData");
                });

            modelBuilder.Entity("ECDLink.DataAccessLayer.Entities.Caregiver.Caregiver", b =>
                {
                    b.Navigation("Grants");
                });

            modelBuilder.Entity("ECDLink.DataAccessLayer.Entities.Classroom.Classroom", b =>
                {
                    b.Navigation("ClassroomGroups");

                    b.Navigation("Programmes");
                });

            modelBuilder.Entity("ECDLink.DataAccessLayer.Entities.Classroom.ClassroomGroup", b =>
                {
                    b.Navigation("ClassProgrammes");

                    b.Navigation("Learners");
                });

            modelBuilder.Entity("ECDLink.DataAccessLayer.Entities.Classroom.Programme", b =>
                {
                    b.Navigation("DailyProgrammes");
                });

            modelBuilder.Entity("ECDLink.DataAccessLayer.Entities.Users.Child", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("ECDLink.DataAccessLayer.Entities.Users.Practitioner", b =>
                {
                    b.Navigation("Documents");
                });
#pragma warning restore 612, 618
        }
    }
}
