module.exports = {
  rules: {
    'body-leading-blank': [1, 'always'],
    'body-max-line-length': [2, 'always', 100],
    'footer-leading-blank': [1, 'always'],
    'footer-max-line-length': [2, 'always', 100],
    'header-max-length': [2, 'always', 100],
    'scope-empty': [0, 'never'],
    'scope-case': [0, 'always', ['lower-case']],
    'subject-case': [
      0,
      'never',
      ['sentence-case', 'start-case', 'pascal-case', 'upper-case'],
    ],
    'subject-empty': [0, 'never'],
    'subject-full-stop': [0, 'never', '.'],
    'type-case': [0, 'always', 'lower-case'],
    'type-empty': [0, 'never'],
    'type-enum': [
      0,
      'always',
      [
        'build',
        'chore',
        'ci',
        'config',
        'docs',
        'feat',
        'fix',
        'perf',
        'refactor',
        'revert',
        'style',
        'test',
      ],
    ],
  },
};
