export enum ContentConsentTypeEnum {
  TermsAndConditions = 'Terms And Conditions',
  DataPermissionsAgreement = 'Data Permissions Agreement',
  PersonalInformationAgreement = 'Personal Information',
  ConsentAgreement = 'Consent Agreement',
  CommitmentAgreement = 'Commitment Agreement',
  IndemnityAgreement = 'Indemnity Agreement',
  PhotoPermissions = 'Photo Permissions',
  LearningThroughPlay = 'Learning Through Play',
  PermissionToShare = 'Permission To Share',
  FranchiseeAgreement = 'Franchisee Agreement',
  ChildProtection = 'Child Protection',
}

export enum ContentTypeEnum {
  ProgrammeRoutine = 1,
  ProgrammeRoutineItem = 2,
  ProgrammeRoutineSubItem = 3,
  ProgressTrackingCategory = 4,
  ProgressTrackingSubCategory = 5,
  ProgressTrackingLevel = 6,
  ProgressTrackingSkill = 7,
  Theme = 8,
  ThemeDay = 9,
  StoryBook = 10,
  StoryBookParts = 11,
  StoryBookPartQuestion = 12,
  Activity = 13,
  Consent = 14,
}
