export enum LocalStorageKeys {
  config = 'ECDConfig',
  user = 'ECDUser',
  theme = 'ECDTheme',
  practitionerProfilePicture = 'PractitionerProfilePicture',
  practitionerProgrammePicture = 'PractitionerProgrammePicture',
  hasViewedJulProgressReport = 'HasViewedJulProgressReport',
  hasViewedDecProgressReport = 'HasViewedDecProgressReport',
  attendanceTutorialComplete = 'AttendanceTutorialComplete',
  programmeWalkthroughComplete = 'programmeWalkthroughComplete',
  hasClosedAttendanceSmartStartPointsMessage = 'HasClosedAttendanceSmartStartPointsMessage',
  HasTrackedChildProgressBefore = 'HasTrackedChildProgressBefore',
  isSmartStartUser = 'IsSmartStartUser',
  coachProfilePicture = 'CoachProfilePicture',
  hasClosedSuccessAttendanceSubmitted = 'hasClosedSuccessAttendanceSubmitted',
  offlineStatments = 'offlineStatments',
  childProfileTutorialComplete = 'childProfileTutorialComplete',
  incomeStatementTutorialComplete = 'IncomeStatementTutorialComplete',
  pointsSubmitStatementsMessageDismissed = 'PointsSubmitStatementsMessageDismissed',
  askToJoinClubViewed = 'AskToJoinClubViewed',
  hasVisitedProgrammeDashboard = 'HasVisitedProgrammeDashboard',
}
