<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<TargetFramework>net7.0</TargetFramework>
	<Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NETCore.Targets" Version="3.0.0" PrivateAssets="all" />
    <PackageReference Include="HotChocolate.AspNetCore" Version="12.12.1" />
    <PackageReference Include="Microsoft.IdentityModel.Tokens" Version="6.25.1" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="7.0.0" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="6.25.1" />
	<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="7.0.0" />
	<PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="7.0.0" />
	  
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\ECDLink.PostgresTenancy\ECDLink.PostgresTenancy.csproj" />
    <ProjectReference Include="..\ECDLink.Core\ECDLink.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Filters\" />
  </ItemGroup>
</Project>
