delete from "MessageTemplate" where "TemplateType" like 'gg-%';
delete from "MessageTemplate" where "TemplateType" = 'three-week-notification' and "Protocol" in ('email', 'hub');
delete from "MessageTemplate" where "TemplateType" = 'four-week-notification' and "Protocol"='email';
delete from "MessageTemplate" where "TemplateType" = 'promoted-to-prinicpal-or-faa' and "Protocol"='sms';
delete from "MessageTemplate" where "TemplateType" = 'marked-onleave' and "Protocol"='hub';
delete from "MessageTemplate" where "TemplateType" = 'removed-from-programme' and "Protocol"='sms';
delete from "MessageTemplate" where "TemplateType" = 'promoted-to-prinicpal-or-faa' and "Protocol"='sms';

delete from "MessageTemplate" where "TemplateType" in ('fillin-self-asessment-form',
'team-lead-portal-invitation',
'email-changed-by-admin',
'trainee-overdue-tasks',
'trainee-setup-venue',
'two-more-steps-to-complete',
'trainee-register-children',
'trainee-sign-agreement',
'trainee-sign-startup-agreement',
'income-statement-not-complete-by-1st',
'clubleader-role-assigned',
'gain-community-support',
'child-document-flagged',
'record-caregiver-meeting',
'user-added-to-club',
'submit-daily-attendance',
'startup-support-ending-in-2months',
'top-smartstarter-points',
'plan-your-programmes',
'endofyear-points-earned',
'monthly-points-reminder-b',
'principal-report-deadline-passed',
'principal-all-reports-done',
'report-deadline-passed',
'start-trainee-journey',
'30days-offline',
'21days-offline',
'coach-visits-overdue',
'coach-remove-trainee',
'league-setup-unassigned-clinics',
'unassigned-clinics',
'duplicate-mother-added',
'duplicate-child-added',
'next-month-meeting-topic-not-added',
'health-care-worker-opted-out',
'clinic-missing-team-lead',
'no-meeting-report-submitted-for-clinic',
'trainee-two-week-onboarding-warning',
'new-clubleader',
'coach-new-trainees',
'coach-visit-requested',
'coach-address-updated-schedule-visit',
'coach-new-practitioners-linked',
'coach-trainee-ready-smartspace-check',
'coach-fillin-self-asessment-form')
