update "MessageTemplate" set "Ordering"= 1 where "TemplateType" in ('principal-invitation', 'ProgrammeInvitation');
update "MessageTemplate" set "Ordering"= 2 where "TemplateType" = 'pre-school-invitation';
update "MessageTemplate" set "Ordering"= 3 where "TemplateType" = 'removed-from-programme  ';
update "MessageTemplate" set "Ordering"= 4 where "TemplateType" = 'promoted-to-prinicpal-or-faa';
update "MessageTemplate" set "Ordering"= 5 where "TemplateType" = 'rejected-invitation';
update "MessageTemplate" set "Ordering"= 6 where "TemplateType" = 'four-week-notification';
update "MessageTemplate" set "Ordering"= 7 where "TemplateType" = 'three-week-notification';
update "MessageTemplate" set "Ordering"= 8 where "TemplateType" = 'practitioner-joined-with-preschool-code';
update "MessageTemplate" set "Ordering"= 9 where "TemplateType" = 'unassigned-classes';
update "MessageTemplate" set "Ordering"= 10 where "TemplateType" = 'marked-onleave';
update "MessageTemplate" set "Ordering"= 11 where "TemplateType" = 'child-unassigned-to-class';
update "MessageTemplate" set "Ordering"= 12 where "TemplateType" = 'submit-weekly-attendance';
update "MessageTemplate" set "Ordering"= 13 where "TemplateType" = 'statements-60-days-notification';
update "MessageTemplate" set "Ordering"= 14 where "TemplateType" = 'statements-30-days-notification';
update "MessageTemplate" set "Ordering"= 15 where "TemplateType" = 'calendar-invitation';
update "MessageTemplate" set "Ordering"= 16 where "TemplateType" = 'reassigned-to-new-class';
update "MessageTemplate" set "Ordering"= 17 where "TemplateType" = 'coach-remove-practitioner';
update "MessageTemplate" set "Ordering"= 18 where "TemplateType" = 'open-community-connections';
update "MessageTemplate" set "Ordering"= 19 where "TemplateType" = 'feedback-notification';