-- Copy ContentType 'Consent' to a new ContentType Called 'ConsentSS', using current Consent datadata
begin transaction;
	-- #1 Add columns for Id mapping
	alter table "Content" add column "OldId" integer null;

	-- -- Remove PK_ContentValue constraint from table as it doesn't and can't include tenantId (due to practise of using nulls)
	alter table "ContentValue" drop constraint "PK_ContentValue";
	alter table "ContentValue" ADD "Id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY;
	-- add a constraint that includes the tenantId
	-- pgsql > 14
	-- alter table "ContentValue" add constraint "u_ContentValue" UNIQUE NULLS NOT DISTINCT ("ContentId", "ContentTypeFieldId", "LocaleId", "TenantId");
--	CREATE UNIQUE INDEX "u_ContentValue" ON "ContentValue" ("ContentId", "ContentTypeFieldId", "LocaleId");
	CREATE UNIQUE INDEX "u_ContentValue_TenantId_Null" ON "ContentValue" ("ContentId", "ContentTypeFieldId", "LocaleId") WHERE "TenantId" IS NULL;

	-- Delete funda Consent content
	delete from "ContentValue"
	where "ContentId" in (select "ContentId" from "Content" where "ContentTypeId" = (select ct."Id" from "ContentType" ct where ct."Name" = 'Consent') and "TenantId" = (select t."Id" from "Tenant" t where "ApplicationName" = 'Funda'));

	delete from "Content"
	where "ContentTypeId" = (select ct."Id" from "ContentType" ct where ct."Name" = 'Consent')
		and "TenantId" = (select t."Id" from "Tenant" t where "ApplicationName" = 'Funda');
	
	-- Make all ContentFieldTypes global.
--	update "ContentFieldType"
--	set "TenantId" = null
--	where "TenantId" is not null;

	-- Make all GG content for Consent global.
	update "Content"
	set "TenantId" = null
	where "ContentTypeId" = (select ct."Id" from "ContentType" ct where ct."Name" = 'Consent')
			and "TenantId" = (select t."Id" from "Tenant" t where "ApplicationName" = 'GrowGreat');

	-- Make all former GG ContentValue for ContentType Consent global, GG is the donor.
	update "ContentValue"
	set "TenantId" = null
	where "Id" in (select c."Id" from "ContentValue"c where c."TenantId" = (select t."Id" from "Tenant" t where "ApplicationName" = 'GrowGreat'));

	
	-- Make GrowGreat content TenantIds consistent for all ContentTypes
	update "Content" 
	set "TenantId" = (select t."Id" from "Tenant" t where "ApplicationName" = 'GrowGreat')
	where "Id" in (select "Id" from "ContentType" where "TenantId" = (select t."Id" from "Tenant" t where "ApplicationName" = 'GrowGreat'));

	-- Make GrowGreat contentValue TenantIds consistent for all ContentTypes
	update "ContentValue"
	set "TenantId" = (select t."Id" from "Tenant" t where "ApplicationName" = 'GrowGreat')
	where "ContentId" in (select "Id" from "Content" where "TenantId" = (select t."Id" from "Tenant" t where "ApplicationName" = 'GrowGreat'));

	
	-- Make Funda content TenantIds consistent for all ContentTypes
	update "Content" 
	set "TenantId" = (select t."Id" from "Tenant" t where "ApplicationName" = 'Funda')
	where "Id" in (select "Id" from "ContentType" where "TenantId" = (select t."Id" from "Tenant" t where "ApplicationName" = 'Funda'));

	-- Make Funda contentValue TenantIds consistent for all ContentTypes
	update "ContentValue"
	set "TenantId" = (select t."Id" from "Tenant" t where "ApplicationName" = 'Funda')
	where "ContentId" in (select "Id" from "Content" where "TenantId" = (select t."Id" from "Tenant" t where "ApplicationName" = 'Funda'));


	-- Add Missing Content items based on existing global content - GrowGreat
	insert into "Content" ("ContentTypeId", "IsActive", "InsertedDate", "UpdatedDate", "UpdatedBy", "TenantId", "OldId")
	select c."ContentTypeId", c."IsActive", CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, c."UpdatedBy", (select t."Id" from "Tenant" t where "ApplicationName" = 'GrowGreat'), c."Id"
	from "Content" c
	inner join "ContentType" ct 
		on c."ContentTypeId" = ct."Id"
	where 
		c."ContentTypeId" is not null
		and ct."Id" = (select ct."Id" from "ContentType" ct where ct."Name" = 'Consent')
		and c."ContentTypeId" = (select ct."Id" from "ContentType" ct where ct."Name" = 'Consent')
		and ct."TenantId" is null
		and c."TenantId" is null;

	-- Copy ContentValues from global tenant - GrowGreat
	insert into "ContentValue" ("ContentId", "LocaleId", "ContentTypeFieldId", "Value", "StatusId", "TenantId")
	select (select "Id" from "Content" c where c."OldId" = cv."ContentId" and c."TenantId" = (select t."Id" from "Tenant" t where "ApplicationName" = 'GrowGreat')), cv."LocaleId", (select "Id" from "ContentTypeField" where "Id" = cv."ContentTypeFieldId"), cv."Value", cv."StatusId", (select t."Id" from "Tenant" t where "ApplicationName" = 'GrowGreat')
	from "ContentValue" cv
	inner join "Content" c
		on c."OldId" = cv."ContentId"
	where c."OldId" is not null 
		and c."ContentTypeId" = (select ct."Id" from "ContentType" ct where ct."Name" = 'Consent')
		and cv."ContentTypeFieldId" is not null
		and c."TenantId" = (select t."Id" from "Tenant" t where "ApplicationName" = 'GrowGreat');

	
	-- Add missing Content based on existing content - Funda
	insert into "Content" ("ContentTypeId", "IsActive", "InsertedDate", "UpdatedDate", "UpdatedBy", "TenantId", "OldId")
	select c."ContentTypeId", c."IsActive", CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, c."UpdatedBy", (select t."Id" from "Tenant" t where "ApplicationName" = 'Funda'), c."Id"
	from "Content" c
	where c."TenantId" = (select t."Id" from "Tenant" t where "ApplicationName" = 'GrowGreat') 
		and c."ContentTypeId" = (select ct."Id" from "ContentType" ct where ct."Name" = 'Consent');

	-- Copy ContentValues from growgreat - Funda
	insert into "ContentValue" ("ContentId", "LocaleId", "ContentTypeFieldId", "Value", "StatusId", "TenantId")
	select (select "Id" from "Content" c where c."OldId" = cv."ContentId" and c."TenantId" = (select t."Id" from "Tenant" t where "ApplicationName" = 'Funda')), cv."LocaleId", (select "Id" from "ContentTypeField" where "Id" = cv."ContentTypeFieldId"), cv."Value", cv."StatusId", (select t."Id" from "Tenant" t where "ApplicationName" = 'Funda')
	from "ContentValue" cv
	inner join "Content" c 
		on c."OldId" = cv."ContentId"
	where c."OldId" is not null 
		and cv."TenantId" = (select t."Id" from "Tenant" t where "ApplicationName" = 'GrowGreat')
		and c."ContentTypeId" = (select ct."Id" from "ContentType" ct where ct."Name" = 'Consent');
	
	-- Clean up
	alter table "Content" drop column "OldId";
	
COMMIT;
-- rollback transaction;