query childrenForClassroomGroup($classRoomGroupId: UUID!) {
  childrenForClassroomGroup(classRoomGroupId: $classRoomGroupId) {
    id
    workflowStatusId
    insertedDate
    allergies
    disabilities
    otherHealthConditions
    otherLanguages
    isActive
    insertedBy
    userId
    user {
      id
      firstName
      surname
      fullName
      email
      genderId
      dateOfBirth
      profileImageUrl
      isActive
      isSouthAfricanCitizen
      verifiedByHomeAffairs
      userLanguages {
        languageId
      }
    }
    caregiverId
    caregiver {
      id
      phoneNumber
      idNumber
      firstName
      surname
      fullName
      siteAddressId
      siteAddress {
        id
        provinceId
        province {
          id
          description
        }
        name
        addressLine1
        addressLine2
        addressLine3
        postalCode
        ward
        isActive
      }
      relationId
      educationId
      emergencyContactFirstName
      emergencyContactSurname
      emergencyContactPhoneNumber
      additionalFirstName
      additionalSurname
      additionalPhoneNumber
      joinReferencePanel
      contribution
      grants {
        id
        description
      }
      isActive
      isAllowedCustody
    }
  }
}
