query coachByCoachUserId($userId: String) {
  coachByCoachUserId(userId: $userId) {
    signingSignature
    id
    startDate
    user {
      id
      userName
      email
      isSouthAfricanCitizen
      verifiedByHomeAffairs
      dateOfBirth
      idNumber
      firstName
      surname
      fullName
      contactPreference
      genderId
      phoneNumber
      profileImageUrl
      roles {
        id
        name
      }
    }
    siteAddressId
    siteAddress {
      id
      provinceId
      province {
        id
        description
      }
      name
      addressLine1
      addressLine2
      addressLine3
      postalCode
      ward
      isActive
    }
    signingSignature
    isActive
    practitionerVisits {
      id
    }
  }
}
