using System.ComponentModel;

namespace ECDLink.Abstractrions.Enums
{
    public enum FileTypeEnum
    {
        [Description("unknown")]
        Unknown,
        [Description("theme")]
        Theme,
        [Description("profile-image")]
        ProfileImage,
        [Description("classroom-profile")]
        ClassroomProfile,
        [Description("child")]
        Child,
        [Description("Practitioner")]
        Practitioner,
        [Description("coach")]
        Coach,
        [Description("care-giver")]
        CareGiver,
        [Description("progress-tracking-category")]
        ProgressTrackingCategory,
        [Description("progress-tracking-sub-category")]
        ProgressTrackingSubCategory,
        [Description("progress-tracking-level")]
        ProgressTrackingLevel,
        [Description("report-templates")]
        ReportTemplates,
        [Description("maternal-case-record")]
        MaternalCaseRecord,
        [Description("road-to-health-book")]
        RoadToHealthBook,
        [Description("content-image")]
        ContentImage,
        [Description("income-statement-pdf")]
        IncomeStatementPDF,
        [Description("attendance-pdf")]
        AttendancePDF,
        [Description("childregistrationform")]
        ChildRegistrationForm, 
        [Description("child-clinic-card")]
        ChildClinicCard, 
        [Description("child-birth-certificate")]
        ChildBirthCertificate,
        [Description("practitioner-agreement")]
        PractitionerAgreement,
        [Description("identity-document")]
        IdentityDocument,
        [Description("proof-of-site-address")]
        ProofOfSiteAddress,
        [Description("startup-support-agreement")]
        StartupSupportAgreement,
        [Description("proof-ofaccount")]
        ProofOfAccount,
        [Description("calendar-event-type")]
        CalendarEventType,
    }
}
