
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apy-k8s-dev-api-@branch
  labels:
    app: apy-k8s-dev-api-@branch
    application: api-@branch
    cluster: 'true'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apy-k8s-dev-api-@branch
  template:
    metadata:
      labels:
        app: apy-k8s-dev-api-@branch
        application: api-@branch
        cluster: 'true'
    spec:
      containers:
        - name: node-api-@branch
          image: apyecdreg.azurecr.io/ecdconnect-api:@version
          imagePullPolicy: IfNotPresent          
          ports:
            - containerPort: 5000
              name: http-api
              protocol: TCP
          livenessProbe:
            failureThreshold: 5
            initialDelaySeconds: 240
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 5000
            timeoutSeconds: 5

---

apiVersion: v1
kind: Service
metadata:
  name: apy-k8s-dev-api-service-@branch
  labels:
    app: apy-k8s-dev-api-@branch
    application: api-@branch
    cluster: 'true'
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: http-api
  selector:
    app: apy-k8s-dev-api-@branch
  sessionAffinity: None
  type: LoadBalancer
