FROM apyecdreg.azurecr.io/apy-node:14.0
#ARG BUILD_VERSION=0  #I'm bypassing the parameter because it fails in Azure
EXPOSE 8080

#RUN printf "BUILD_VERSION=$version"

COPY ./app-lxp-$version.zip /src/app-lxp.zip
COPY ./docker-entrypoint.sh /src/docker-entrypoint.sh
RUN  chmod +x /src/docker-entrypoint.sh

ENTRYPOINT ["/src/docker-entrypoint.sh"]
