
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apy-k8s-dev-fe-$branch
  labels:
    app: apy-k8s-dev-fe-$branch
    application: fe-$branch
    cluster: 'true'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apy-k8s-dev-fe-$branch
  template:
    metadata:
      labels:
        app: apy-k8s-dev-fe-$branch
        application: fe-$branch
        cluster: 'true'
    spec:
      containers:
        - name: node-fe-$branch
          image: apyecdreg.azurecr.io/ecdconnect-ef:$version
          ports:
            - containerPort: 8080
              name: http-fe
              protocol: TCP
          livenessProbe:
            failureThreshold: 5
            initialDelaySeconds: 240
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 8080
            timeoutSeconds: 5

---

apiVersion: v1
kind: Service
metadata:
  name: apy-k8s-dev-fe-service-$branch
  labels:
    app: apy-k8s-dev-fe-$branch
    application: fe-$branch
    cluster: 'true'
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: http-fe
  selector:
    app: apy-k8s-dev-fe-$branch
  sessionAffinity: None
  type: LoadBalancer
