<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
	<TargetFramework>net6.0</TargetFramework>
    <UserSecretsId>dotnet-ECDLink.AutomatedServiceWorkers-59BE6C62-491F-4ED6-A43D-46BA4C7ACF3E</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerfileContext>..\..</DockerfileContext>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Cronos" Version="0.7.1" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="6.0.0" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.17.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\ECDLink.Tenancy\ECDLink.Tenancy.csproj" />
    <ProjectReference Include="..\..\Libraries\Modules\ECDLink.DataAccessLayer\ECDLink.DataAccessLayer.csproj" />
    <ProjectReference Include="..\..\Libraries\Modules\ECDLink.SmartStart\ECDLink.SmartStart.csproj" />
  </ItemGroup>
</Project>
