export const NavigationNames = {
  Home: 'Home',
  Profile: {
    Profile: 'Profile',
    Account: 'Account',
    Preschool: 'Preschool',
    Journey: 'Journey',
  },
  Classroom: {
    Classroom: 'Classroom',
    Classes: 'Classes',
    Attendance: 'Attendance',
    Progress: 'Progress',
    Activities: 'Activities',
    Resources: 'Resources',
    Practitioners: 'Practitioners',
    Programme: 'Programme',
  },
  Business: {
    Business: 'Business',
    Staff: 'Staff',
    Money: 'Money',
    Resources: 'Resources',
  },
  Community: {
    Community: 'Community',
    Resources: 'Resources',
  },
  Training: 'Training',
  Points: 'Points',
  Messages: 'Messages',
  SmartStarters: 'Practitioners',
  Calendar: 'Calendar',
  Logout: 'Log out',
};
