<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Configuration\Setup\Seed\SeedData\Programme\**" />
    <Compile Remove="Entities\Classroom\ProgressTracking\**" />
    <Compile Remove="Entities\Programme\**" />
    <EmbeddedResource Remove="Configuration\Setup\Seed\SeedData\Programme\**" />
    <EmbeddedResource Remove="Entities\Classroom\ProgressTracking\**" />
    <EmbeddedResource Remove="Entities\Programme\**" />
    <None Remove="Configuration\Setup\Seed\SeedData\Programme\**" />
    <None Remove="Entities\Classroom\ProgressTracking\**" />
    <None Remove="Entities\Programme\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Audit.EntityFramework.Core" Version="18.1.5" />
    <PackageReference Include="Audit.EntityFramework.Identity.Core" Version="18.1.5" />
    <PackageReference Include="Audit.NET.AzureStorage" Version="18.1.5" />
    <PackageReference Include="MediatR" Version="9.0.0" />
    <PackageReference Include="MediatR.Extensions.Microsoft.DependencyInjection" Version="9.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.ApiAuthorization.IdentityServer" Version="3.1.16" />
    <PackageReference Include="Microsoft.AspNetCore.Identity" Version="2.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="5.0.7" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="5.0.7" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="5.0.7">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="5.0.0" />
    <PackageReference Include="Microsoft.Extensions.Identity.Core" Version="5.0.13" />    
    <PackageReference Include="NJsonSchema.CodeGeneration" Version="10.4.4" />
    <PackageReference Include="NJsonSchema.CodeGeneration.CSharp" Version="10.4.4" />
    <PackageReference Include="NJsonSchema.CodeGeneration.TypeScript" Version="10.4.4" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="5.0.7" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\ECDLink.AzureStorage\ECDLink.AzureStorage.csproj" />
    <ProjectReference Include="..\ECDLink.Abstractrions\ECDLink.Abstractrions.csproj" />
    <ProjectReference Include="..\ECDLink.Core\ECDLink.Core.csproj" />
    <ProjectReference Include="..\ECDLink.Security\ECDLink.Security.csproj" />
  </ItemGroup>

</Project>
