<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<TargetFramework>net7.0</TargetFramework>
	<Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
	  <PackageReference Include="System.Linq.Expressions" Version="4.3.0" />
	  <PackageReference Include="HotChocolate.Abstractions" Version="12.12.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DataAccess\ECDLink.ContentManagement\ECDLink.ContentManagement.csproj" />
    <ProjectReference Include="..\ECDLink.DataAccessLayer\ECDLink.DataAccessLayer.csproj" />
    <ProjectReference Include="..\ECDLink.GraphQL\ECDLink.EGraphQL.csproj" />
    <ProjectReference Include="..\ECDLink.PDFGenerator\ECDLink.PDFGenerator.csproj" />
  </ItemGroup>

</Project>
